### ISSUE TITLE
Range error on shim-array

### ISSUE THREAD

**Issue by aaronkbutler** [NorthernMan54/homebridge-alexa#481] opened 2021-12-25 16:15 UTC
I’m getting an error in the Homebridge console every few minutes which causes Homebridge to restart.

![61177D18-751C-40CA-ACC8-A65586682C54](https://user-images.githubusercontent.com/46665383/147389132-ac858ecf-c62a-4a37-9b65-78c3a8ce4aae.jpeg)

**Comment by NorthernMan54** [comment] 2021-12-25 16:48
Something weird is happening here.  The package collections and shim-array are not a dependency of homebridge-alexa.  Did you make any recent changes or are you running something non-standard ?

Have you tried removing the plugin and re-installing ?

**Comment by aaronkbutler** [comment] 2021-12-25 19:26
The issue seems to arise whenever I set routines to true in my config.

**Comment by aaronkbutler** [comment] 2021-12-25 19:38
Turned out to be an issue with another plugin I was using. Once I got rid of that, I was able to enable routines and everything runs smoothly.

**Comment by NorthernMan54** [comment] 2021-12-25 20:05
Which plugin ?

**Comment by aaronkbutler** [comment] 2021-12-25 21:24
homebridge-myq

**Comment by NebzHB** [comment] 2021-12-26 16:45
Hello @NorthernMan54, it seems the package collections is used by the packages mqtt you have dependencies on. I haven't got the problem myself, but I've encountered it on users using other plugins than the one mentioned by @aaronkbutler. I ask the plugin list to the users who had the problems.

**Comment by NorthernMan54** [comment] 2021-12-26 17:12
@NebzHB I went and looked at the collections package, and they have this issue mentioned

https://github.com/montagejs/collections/issues/241

need to read it in detail to see what they are saying

**Comment by NebzHB** [comment] 2021-12-26 17:14
It seems they fixed it in march (with a quick overview of the issue)...

**Comment by NebzHB** [comment] 2021-12-26 21:36
Hello again @NorthernMan54,

I see you are using a version 2.x of mqtt. And they are version 4.x, could it be that ?

i have the plugin list of one of my users : 
homebridge-ring
homebridge-adb 
homebridge-broadlink-rm-pro (using mqtt 4.x)
homebridge-ewelink
homebridge-config-ui-x
homebridge-camera-ffmpeg

**Comment by NorthernMan54** [comment] 2021-12-27 04:30
I have a major renovation planned for this winter, and that is one of many items on the backlog.

**Comment by NebzHB** [comment] 2021-12-27 08:51
have a third user with the problem : Rpi3+/bluster, i'm waiting for his plugin list

**Comment by NebzHB** [comment] 2021-12-27 09:25
i can reproduce on my debian vm !
tried to install collections globally but it's still installed by homebridge-alexa in his node_modules folder...

**Comment by NorthernMan54** [comment] 2021-12-27 15:42
@NebzHB Well I was able to recreate the issue by installing myq into my development environment.  So far I have tried updating the mqtt package version to the latest version, nope, and then tried the same version as  myq, same.  I then went and implemented the collections fix to homebridge-alexa ie added `"collections": "github:montagejs/collections#85f00f8",` to package.json, same.  I then added it to myq as well, and success.

Am thinking the only true fix is to have collections package publish the release.

**Comment by NebzHB** [comment] 2021-12-28 07:00
strange.. none of my users uses myq... for my part, i fixed it with adding if(!Array.from) {} wrap around the function re-defining Array.from in collections (as proposed in one of their PR (#https://github.com/montagejs/collections/pull/212)). I see in original Issue of Collections that camera-ffmpeg does have the issue too (#https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1240)

**Comment by NebzHB** [comment] 2021-12-28 10:04
Another user with mqttthings plugin

**Comment by NorthernMan54** [comment] 2021-12-28 15:09
@aaronkbutler if you can try updating to the latest version, I implemented a workaround for the issue.

**Comment by NebzHB** [comment] 2021-12-28 15:15
your fix works for me :)

**Comment by NorthernMan54** [comment] 2021-12-29 02:22
Tks closing this

**Closed by NorthernMan54** 2021-12-29 02:22 UTC

**Comment by aaronkbutler** [comment] 2021-12-29 03:01
> @aaronkbutler if you can try updating to the latest version, I implemented a workaround for the issue.

Thanks for working on this! Works great now.
