### ISSUE TITLE
Homebridge Thermostat Not working

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#279] opened 2019-12-16 17:52 UTC
I have a thermostat setup in Homebridge.  When I use the Alexa app to open the thermostat, it say's it's not responding and Homebridge scrolls "ERROR: alexaStateResponse getaddrinfo ENOTFOUND undefined"

**Comment by NorthernMan54** [comment] 2019-12-16 21:22
Please have alexa discover devices again

**Comment by meluvalli** [comment] 2019-12-17 00:53
Logged into alexa.amazon.com, delete all devices.  Rediscovered devices.  Same result.

**Comment by NorthernMan54** [comment] 2019-12-18 01:28
Can you share an accessory dump?  details for how to collect one are here

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by meluvalli** [comment] 2019-12-20 09:31
Sorry for the delay on this!  Here is the dump you requested:

<pre>
{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge for Homeseer","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"XX:XX:XX:XX:XX:XX","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.50","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]},{"aid":50,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HomeSeer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Z-Wave Sensor Multilevel","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Thermostat.Home","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HS Thermostat ref 504","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"0000004A-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"0000000F-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":0,"description":"Current Heating Cooling State","valid-values":[0,1,2],"maxValue":2,"minValue":0},{"iid":10,"type":"00000033-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":1,"description":"Characteristic.TargetHeatingCoolingState","valid-values":[0,1,2,3],"maxValue":3,"minValue":0},{"iid":11,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":23.8,"description":"Characteristic.CurrentTemperature","unit":"celsius","maxValue":50,"minValue":-20,"minStep":0.1},{"iid":12,"type":"00000035-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":21.1,"description":"Characteristic.TargetTemperature","unit":"celsius","maxValue":38,"minValue":10,"minStep":0.1},{"iid":13,"type":"00000036-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":1,"description":"Temperature Display Units","valid-values":[0,1],"maxValue":1,"minValue":0},{"iid":14,"type":"00000012-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Characteristic.HeatingThresholdTemperature","unit":"celsius","maxValue":25,"minValue":0,"minStep":0.1},{"iid":15,"type":"0000000D-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":10,"description":"Characteristic.CoolingThresholdTemperature","unit":"celsius","maxValue":35,"minValue":10,"minStep":0.1}],"primary":false,"hidden":false}]}]}
</pre>

To make it easier on you to read, I removed ALL devices except my thermostat.  :)

**Comment by NorthernMan54** [comment] 2019-12-21 00:28
This is a duplicate of #274, the homeseer plugin does funny things with the characteristic description property which breaks my plugin.  It technically does not break the HomeKit spec, but breaks how my plugin determines device characteristics.

To fix I need to rework the characteristic determination logic, which is a significant rework of the logic to determine device characteristics.  I have added it to me next major change, so will be a few weeks.

**Comment by NorthernMan54** [comment] 2019-12-21 00:30
PS This is what Alexa is receiving for this thermostat, it is missing the control functions...

node newParseAccessories.js ~/Desktop/issue_279.json 
Alexa Message Validation Passed!

-----------------------------------------------------------

{
    "event": {
        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover.Response",
            "payloadVersion": "3",
            "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
        },
        "payload": {
            "endpoints": [
                {
                    "endpointId": "Q0M6MjI6M0Q6RTM6Q0U6MzAtcGFyc2VUZXN0LUhvbWVTZWVyLVRoZXJtb3N0YXQuSG9tZS0wMDAwMDA0QS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=",
                    "friendlyName": "Thermostat.Home",
                    "description": "parseTest Thermostat.Home Thermostat",
                    "manufacturerName": "HomeSeer",
                    "displayCategories": [
                        "THERMOSTAT"
                    ],
                    "cookie": {
                        "thermostatMode": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":50,\"iid\":9}",
                        "ReportState": "[]"
                    },
                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.ThermostatController",
                            "version": "3",
                            "properties": {
                                "supported": [],
                                "proactivelyReported": false,
                                "retrievable": true
                            },
                            "configuration": {
                                "supportsScheduling": false,
                                "supportedModes": [
                                    "HEAT",
                                    "COOL",
                                    "AUTO",
                                    "OFF"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    }
}

-----------------------------------------------------------

**Comment by NorthernMan54** [comment] 2019-12-22 15:37
@meluvalli after discussing with the home seer plugin dev he made a change that should resolve this.  If you could update the homeseer plugin, and discover devices you should be good.

Alternatively he suggested to update to his improved homeseer plugin, homebridge-homeseer4

@jvmahon thanks for resolving this, much appreciated

**Comment by meluvalli** [comment] 2019-12-22 15:48
I am so sorry!  I didn’t realize he fixed this issue on his end 😀. I have
been working with jvmahon  <https://github.com/jvmahon>for the last few
days on the homeseer4 plug-in!  That’s what I’m running 😀

You are correct, it now shows up and responding! However, something is
majorly wrong with it!

Home kit shows this (and is correct):



Alexa shows this and is NOT correct:

**Comment by meluvalli** [comment] 2019-12-22 16:03
Ok, after asking Alexa what temperature it is inside, she responded saying it is 22.2 degrees!  BRR!  That's cold haha!  I think it's reading it in Celsius and I have it set for Fahrenheit. 

I can confirm the google plugin is working and reads everything correctly, however this one is not.

**Comment by NorthernMan54** [comment] 2019-12-22 16:25
It’s likely my wiring of HomeKit to Alexa isn’t accurate, will need to look at that further.  Looking at your screen shot it says current temp of 72, but she is saying 22, that is weird.  Internally HomeKit uses Celsius, and everything I pass to Alexa is in Celsius but she should convert based on your preferences

I’m out of the country right now, will be next week before I can dig further

**Comment by meluvalli** [comment] 2019-12-22 16:29
Ok.  I’ll keep an eye out and let you know if I discover anything else
strange.  I know on the HomeSeer plug-in, he made changes because
Fahrenheit/Celsius issues as well.  So maybe that has something to do with
it.

I appreciate you looking into it when you get back!  Safe travels and have
a Merry Christmas!

**Comment by jvmahon** [comment] 2019-12-22 18:42
Another suggestion, you can also try separating your homebridge plugins (“platforms”) so that different plugins run on different homebridge instances. That would help isolate the HomeSeer plugin from any others and would increase parallelism.  Look here for instructions:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Running-Multiple-Instances-of-HomeBridge

In the past, I’ve found this the ‘best’ way to address conflicts / slowdowns caused by mixing plugins that don’t quite seem to work well together.

**Comment by meluvalli** [comment] 2019-12-22 19:07
I have had issues running Alexa plugin restricted on instances...  I'm not sure what I could be doing wrong, but anytime I add the "filter" command in the config like so:
<pre>
        {
            "platform": "Alexa",
            "name": "Alexa",
            "username": "meluvalli",
            "password": "XXXXXXXX",
            "pin": "XXXXXX",
            "filter": "10.40.162.90:51801"
        }
</pre>

I receive "ERROR: HAP Discovery failed".  However, if I remove the "Filter", it works fine.

![Alexa-Instance](https://user-images.githubusercontent.com/8729476/71326122-fb310700-24bb-11ea-9060-da4500f348f6.png)

**Comment by NorthernMan54** [comment] 2019-12-22 19:28
With the DEBUG flag set it gives a lot more detail of the discovery phase, it you share a log from that we may be able to figure out why filter doesn’t work

**Comment by meluvalli** [comment] 2019-12-22 19:54
You are 100% correct.  It did help figure it out :).   But, why?

I have multiple Ethernet interfaces on this machine.  I only want to bind it to my main IP (10.40.162.90) as shown above, but for some reason HAP is binding to another interface?

Any idea how to fix this?  I already use the "mDNS" flag in my configuration!

<pre>
 hapNodeJSClient Filtered HAP instance address: Homebridge Instance 1 for Homeseer -> XX_XX_XX_XX_XX_XX.local -> 169.254.219.70:51801 +9ms
</pre>

**Comment by NorthernMan54** [comment] 2019-12-22 20:37
I’m not familiar with that option, but if your good at following code, the behind the scene details are here.

https://github.com/KhaosT/HAP-NodeJS/blob/bd7eb986084a4a5898287c7d24a060394ac45008/src/lib/Advertiser.ts#L25

**Comment by meluvalli** [comment] 2019-12-22 21:30
Well, for the sake of maybe helping others incase they come across this thread, I found a "hackish" workaround :)

If you edit the bonjour-hap "service.js" file in /homebridge/node_modules/bonjour-hap/lib folder, you can force it to only use a single interface/IP!

In my case, I had to change the auto-discovering function completely starting at line 107, I changed lines 107-121:

Original value:
<pre>
    var interfaces = os.networkInterfaces()
    for (var ifaceID in interfaces) {
      var iface = interfaces[ifaceID]
      for (var i = 0; i < iface.length; i++) {
        var address = iface[i]
        if (address.internal) { continue }

        records.push(
                    address.family === 'IPv4'
                    ? this._rrA(address.address)
                    : this._rrAaaa(address.address))
      }
    }

    return records
</pre>

I updated it to the below values to force ONLY listening to my IP address I want (in my case 10.40.162.90)
<pre>
    var interfaces = os.networkInterfaces()
    for (var ifaceID in interfaces) {
      var iface = interfaces[ifaceID]
      for (var i = 0; i < iface.length; i++) {
        var address = iface[i]
        if (address.internal) { continue }

//        records.push(
//                    address.family === 'IPv4'
//                    ? this._rrA(address.address)
//                    : this._rrAaaa(address.address))

      }
    }
	records.push(this._rrA('10.40.162.90'));

    return records
</pre>

Notice I remove auto discovering to scan my interfaces and added in (hard coded) my IP address. 

This fixes the problem with discovery!

**Closed** 2019-12-29 14:44 UTC
