### ISSUE TITLE
2nd Gen Echo not discovering any devices

### ISSUE THREAD

**Issue by steverdunn** [NorthernMan54/homebridge-alexa#32] opened 2017-11-10 09:48 UTC
I am having issues, with a New echo 2nd Gen discovering home bridge,

I believe it is expecting a message like

// M-SEARCH * HTTP/1.1
// HOST: 239.255.255.250:1900
// MAN: "ssdp:discover"
// MX: 15   - Up to 15 seconds to respond, have also seen 3
// ST: urn:schemas-upnp-org:device:basic:1

turning on some debug in ssdp.js, I only see the following being received from the echo (192.168.1.75)

 ssdp  from 192.168.1.75:50000 +35ms
 ssdp { MX: '3',
 ssdp   ST: 'upnp:rootdevice',
 ssdp   HOST: '239.255.255.250:1900',
 ssdp   MAN: '"ssdp:discover"' } +0ms
 ssdp sleep for 1052 +1ms
 ssdp << server got: M-SEARCH * HTTP/1.1
 ssdp MX: 3
 ssdp ST: ssdp:all
 ssdp HOST: 239.255.255.250:1900
 ssdp MAN: "ssdp:discover"
 ssdp
 ssdp  from 192.168.1.75:50000 +1ms
 ssdp { MX: '3',
 ssdp   ST: 'ssdp:all',
 ssdp   HOST: '239.255.255.250:1900',
 ssdp   MAN: '"ssdp:discover"' } +0ms

Any assistance appreciated

**Comment by NorthernMan54** [comment] 2017-11-10 11:53
Steve,

The code is looking for a ssdp message like this.

//debug(ssdpMsg);
if (msg.indexOf('ssdp:discover') > 0 && msg.indexOf('urn:schemas-upnp-org:device:basic') > 0) {

I’m thinking remove the test for “urn:schematic....”

**Comment by steverdunn** [comment] 2017-11-10 12:08
I have tried that - and still does not discover any devices, although I do get

**Comment by NorthernMan54** [comment] 2017-11-11 00:52
I added more verbose debugging, could you reinstall and try again with debugging enabling, then post the logs.  The long version of the logs is fine.

**Comment by steverdunn** [comment] 2017-11-11 07:20
I have updated and re-run discovery, the log is here 

https://pastebin.com/MfzRHgJ0

**Comment by NorthernMan54** [comment] 2017-11-11 14:11
@sm17h85 I think both yourself and Steve are having the same issue with the echo 2.  Tks very much for the logs, I can see how far they are getting thru the discovery process, and your both stuck at the same step.  When Alexa does device discovery, the flow looks like this 

1 - Receive - SSDP M-Search - The search parameters changed from the V1 to V2
2 - Send     - SSDP Discovery Response
3 - Receive - GET /description.xml
4 - Send      - Description response
5 - Receive - HTTP request: /api/pkBovaHrTjmiUwGqH7m6q7eecgD3VXVrR3BPE1qK/lights
6 - Send      - Description of all devices

And looking at both flows, homebridge never receives step 5, which means the V2's don't like the description response.  For the description response, I'm using the response from my V1 Hue hub as a template.  Let me think about this further.

**Comment by NorthernMan54** [comment] 2017-11-11 14:26
I went back and looked more closely at the description response, and it was from a Hue V2 hub, and not a V1 hub as I had originally thought.  I have changed the response to now be a V1.  Can you reinstall and try again.  If this isn't successful, logs would be appreciated.  I also changed the debugging to focus on the description response.

**Comment by sm17h85** [comment] 2017-11-11 14:39
I will do that soon and keep you updated.

**Comment by steverdunn** [comment] 2017-11-11 17:16
Thanks for your help - but unfortunately no difference

Logs here https://pastebin.com/VPm60Ehf

**Comment by sm17h85** [comment] 2017-11-11 18:46
same result with my test 

Log: https://pastebin.com/ukArWg3Z

**Comment by NorthernMan54** [comment] 2017-11-11 21:24
I took a look at bwssystems habridge, which uses the same Philips hue hub emulation approach, and did not see any recent issues posted similar to this. But I did see some comments about usage of port 80.  I was wondering if you could retry, but change the homebridge port from 51826 to 80.  As using port 80 requires root, and changing homebridge to run as root is messy.  I would not recommend doing it unless your are very comfortable with it.

As easy approach might be to copy your existing config.json to root’s .homebridge directory, change the homebridge port to 80.  Then start it.

**Comment by steverdunn** [comment] 2017-11-11 21:39
I have tried on port 80 - same result

log here https://pastebin.com/YgcK4xB1

**Comment by NorthernMan54** [comment] 2017-11-12 13:06
I was wondering if you could try bwssystem habridge? If this works, then the problem is my code, if it doesn’t work then it is something else.

**Comment by chrismillsuk** [comment] 2017-11-16 16:01
Firstly I tried the latest version of this software with an echo plus, i had the same results as described here. I have now installed HA-BRIDGE and the echo plus picks up the devices configured with it. I have noticed in the echo notes that it says if you have a HUE v1 you must press the link button before the echo can detect it - the HA-BRIDGE software seems to emulate this when the server starts could this be whats missing?

**Comment by steverdunn** [comment] 2017-11-16 16:14
I did a quick test with HA-Bridge - no devices were picked up by 2nd Gen.

**Comment by chrismillsuk** [comment] 2017-11-16 16:31
At first my echo plus didn’t find anything, I gave up turned off pi, next day started pi opened Alexa app and devices where all there... and when I had more device and rediscover they now show up - after starting up habridge I’m not sure if you have a short period of time to get echo to connect I think it emulates pressing the link button on hue hub

**Comment by NorthernMan54** [comment] 2017-11-16 17:19
I’m in the process of ordering a 2nd Gen device so I can test further.  It should be here next month ( they just released in Canada, and are shipping Dec 5th ).

**Comment by ToddGreenfield** [comment] 2017-11-16 18:58
All 3 of my echo dots are are 2nd Gen. I am not having any issues discovering devices or losing all devices.

**Comment by NorthernMan54** [comment] 2017-11-17 02:51
I checked, and my Echo dot is a second generation as well.  But I think that the problem being reported by @chrismillsuk and @steverdunn is with the new Echo released just recently and the Echo Plus.

Also I was reading the Devices help page on the app, and if you scroll to the bottom, you can see that this approach is still supported and documented ( Hue Hub Emulation ).  I think that there is something Alexa doesn't like with my response to the /description.xml request.  Just need to figure out what the issue is.

So far we have tried

1) Change description.xml response from a hue v2 response to a hue v1 response

2) Change port from 51826 to 80

The next steps for me, is to purchase a new Echo or Echo Plus, and attempt to debug the issue.  I have a Hue v1 hub that I can include in the debugging, in case there is a missing message or something.

**Comment by NorthernMan54** [comment] 2017-12-05 00:04
@steverdunn @ToddGreenfield @chrismillsuk I just received confirmation that my Echo V2 is arriving on Wednesday, December 6.

**Comment by chrismillsuk** [comment] 2017-12-05 07:45
Let me know if you want me to test or try anything once your ready.

**Comment by NorthernMan54** [comment] 2017-12-06 00:40
And it arrived a day early.   And can confirm that there are issues.   First issue I found is that it only talks to emulated hue devices running on port 80.  So everyone would need to move their homebridges from 51826 to port 80.  And it then starts to talk to homebridge, but they changed the pairing sequence slightly and it fails.  I'm going to need a day or 2 to make the adjustments.

**Comment by NorthernMan54** [comment] 2017-12-09 01:02
I'm still looking at this, but it gets stuck 1/2 thru the pairing process.  I'm going to need to spend a few hours tomorrow on this.

**Comment by NorthernMan54** [comment] 2017-12-09 14:22
This is not good.  The approach I'm following to connect Homebridge to Alexa, is to have Homebridge emulate a Philips Hue V1 Hub.  And I just went and tried to connect my real Philips Hue V1 hub with my Echo 2nd Generation and it does not work.   I even have the Hue smart home skill enabled.

I'm going to open a support ticket with Amazon, as the documentation says its supported.

![img_1756](https://user-images.githubusercontent.com/19808920/33796445-701f16cc-dcc2-11e7-8d02-1aea12b2b5e6.PNG)

**Comment by sumpy** [comment] 2017-12-09 18:14
Thank you for all your work with this. I certainly hope that you find a fix for this. I just received my 2nd Gen echo and was looking forward to getting Alexa integration with my current HomeKit devices..

**Comment by ttubbie** [comment] 2017-12-10 15:59
Thanks for your effort in this project as well. I also played around a little with:
- Echo 2nd gen (does not find devices)
- Alexa project on PI (does not find devices)
- dot 2nd gen (DOES FIND ALL DEVICES)

Eventually this observation might help you!

**Comment by kernelheap** [comment] 2017-12-10 19:50
I have a echo dot 2nd gen. It used to work fine until few days back. It is not able to discover devices now. Echo dot seems to be working for everybody else in this thread. I even tried a different amazon account and changed the homebridge port to 80. Any suggestions.

**Comment by NorthernMan54** [comment] 2017-12-11 01:33
Well after resetting everything, I have managed to get my Echo 2nd generation to talk to my Hue V1 hub.  But still can't get my Homebridge-Alexa to talk to my Echo 2nd generation.

**Comment by NorthernMan54** [comment] 2017-12-12 02:59
I spent about 3 hours on chat today with Amazon, this is what they said

```
Justin: I have successfully check my other resource here, I can now verify that emulated hue hub doesn't work for the mean time in Echo devices that was purchased in amazon.ca, since we just recently launch the device here in Canada.
Me: Okay
Justin: No worries emulated hue hub are now on it's way to be available as well in Canada since our developers are now taking care of it.
It's okay Sean, it is your right to know the feature of your purchased device. :)
Me: Tks, I really appreciate your time tonight. Tks very much. I guess I need to wait a bit
Justin: You are most welcome. :)
Me: Have a good evening. Thank you
Justin: I really appreciate your kind consideration and patience regarding this Sean.
Me: Bye
Justin: Yes Sean, I will also send this to our developers so that they can taken care of this as soon as possible.
```

It looks like the newer 2nd generation devices may be supported in the future.....But not now.

**Comment by chrismillsuk** [comment] 2017-12-12 18:39
Hi Does HA-BRIDGE use a different approach? i thought that used Hue emulation? My echo plus (2nd Gen) works fine with HA-Bridge.

**Comment by chrismillsuk** [comment] 2017-12-12 19:04
I have the Echo plus (2nd Gen) which as the built in home hub, I've then got a Raspberry Pi 3 Running HA-Bridge at the minute (ideally Homebridge for home kit integrations as well). At first i had a few issues with the auto discover but i found by doing a discover scenes and then auto discover in the alexa app my devices appeared and have worked ever since in the Alexa App. I using this approach to enable me to use a multitude of x10 devices i have.

**Comment by sumpy** [comment] 2017-12-12 19:45
Chrismillsuk, Are you located in Canada or the US? Were your devices purchased for the american or canadian markets?
From what I have been gathering from those who have been having issues, the emulated hue is having issues with canadian echo's .. Northerman's conversation with amazon seems to confirm that as well as I have seen other sources state that amazon has told them the canadian units were not supporting the 1st gen echoes

**Comment by NorthernMan54** [comment] 2017-12-12 19:52
Just to add to the country conversation 

My echo Dot 2nd generation was purchased out of the US last spring, and my Echo 2nd generation was purchased in Canada.  Both have been reset to English canada.

**Comment by steverdunn** [comment] 2017-12-12 20:03
My 2nd gen echo (with issues) and 2nd gen dot (without) were both purchased in the UK in the past 6 weeks

**Comment by sumpy** [comment] 2017-12-12 20:09
I've got a 2nd Gen echo purchased in Canada as well as a 2nd Gen Dot also purchased in Canada which I just received yesterday.. I will try loading the emulated Hue component again tonight and see if I can get it to work with my Dot .. If it works as long as the Dot is connected , that is a workable solution for me until full support is provided

**Comment by ttubbie** [comment] 2017-12-12 20:20
I have purchased my dot and echo Three weeks ago in Germany.. And get it only to work with 2nd gen dot. Echo 2nd gen alone in network does Not find homebridge.

**Comment by chrismillsuk** [comment] 2017-12-12 20:42
I purchase echo from amazon uk in the last 2 months, it is the plus version with built in hub, I have a second gem echo and second gem dot but the wife as wrapped them for Christmas! So can’t try anything in those until 25th!!!

**Comment by NorthernMan54** [comment] 2017-12-13 03:03
Tonight I tried both HA-Bridge and node-red/alexa-local and neither worked with my Echo 2nd Gen.

I think what we are seeing is the Dot 2nd Gen and Echo Plus 2nd work, while Echo 2nd Gen does not.

@chrismillsuk A fellow X10 fan, its awesome to see a fellow user.  I have about a dozen or so x10 devices as well.

**Comment by chrismillsuk** [comment] 2017-12-13 07:42
Some users have reported the release of ha-bridge 5.1.0 worked first time I haven’t tried it yet, my 2nd gen took awhile to detect my devices once ha-bridge was up I rebooted echo and then did discover scenes then discover devices in the app.

**Comment by NorthernMan54** [comment] 2017-12-16 21:11
Everyone,

I'm parking this for now until, as I can't seem to determine why it is no longer working.   I'm thinking that Amazon did something similar to Google, in that they are checking against the Philip's site for a real hub.   But all hope is not lost for people with a Echo 2nd Generation, who want to integrate with Homebridge.  Next month I'm going to go the the Alexa Home Skill based approach, and have been looking at this as inspiration on the build.

https://alexa-node-red.bm.hardill.me.uk/docs

I'm thinking of something along the same design as that, with no need to poke a hole in your firewall.  And as bonus it will be able to support the full Alexa home skill API!!!

At this time I'm going to update the README to indicate the lack of support for the Echo 2nd generation, until something changes.

**Comment by paulobriennz** [comment] 2017-12-25 09:42
thanks for all your work on this @NorthernMan54  - interested to see this as an alexa skill!

**Comment by NorthernMan54** [comment] 2018-01-12 00:10
Over the next few months, you will be able to view progress on this via a branch of this repository I have created.

https://github.com/NorthernMan54/homebridge-alexa/tree/Alexa2ndGen

**Closed** 2018-01-17 02:14 UTC
