### ISSUE TITLE
Alexa doesn't recognize Max! Cube Bridge devices

### ISSUE THREAD

**Issue by fazerize** [NorthernMan54/homebridge-alexa#137] opened 2018-11-02 21:23 UTC
Maybe you could add support for the discovered Max! Bridge devices.

Plugins name is homebridge-platform-maxcube

I dont know why it only sees the Max Cube but not its devices.

**Comment by NorthernMan54** [comment] 2018-11-02 21:46
I think it is based on which devices are currently supported by homebridge-alexa.  Which device types does max cube support and are you using?  I looked at the max cube quickly and I saw thermostats, which aren’t supported.

**Comment by fazerize** [comment] 2018-11-02 21:47
Will they be supported someday?

**Comment by NorthernMan54** [comment] 2018-11-03 01:29
Someday, I really hoping someone with take up the baton and submit a pull request with the feature

**Comment by fazerize** [comment] 2018-11-03 07:07
Could you code it in if i give you my accessories json?

**Comment by fazerize** [comment] 2018-11-05 11:34
I would help you out with programming but im not into this alexa skills and so on, so working into it would take too much time :/

**Comment by NorthernMan54** [comment] 2018-11-07 15:08
I haven’t looked at the code, as I’m at work and can’t open zip files, but the event listener is in web.js. In web.js you need to map the Alexa API message to a homebridge request.

PS For code management, I presume you have forked my repository on GitHub and are  working from there.   If you can check it back into your fork, I can view your changes there.  Also this is needed prior to your submitting a pull request when it’s complete and working.

**Comment by fazerize** [comment] 2018-11-07 15:59
https://github.com/fazerize/homebridge-alexa-faze

just check it out there :)

**Comment by NorthernMan54** [comment] 2018-11-07 18:47
Tks, on first pass it looks correct but the devil is in the details.

In alexatranslator, / target temperature the heart of it is the cookie field.  The Cookie maps into haAction in web.js, which is the used to form the HAP / homebridge command to control the device.  If they aren’t in alignment, control will fail.

The cookie name field, needs to match the Alexa header.name and the cookie values need to be the correct ones for the HAP request.

Once that is aligned, it should start to work

**Comment by NorthernMan54** [comment] 2018-11-08 00:53
@fazerize I'm closing this as it is a duplicate of #120, lets continue the conversation there

**Closed by NorthernMan54** 2018-11-08 00:53 UTC
