### ISSUE TITLE
app only works for a while

### ISSUE THREAD

**Issue by WinfriedO** [NorthernMan54/homebridge-alexa#469] opened 2021-09-25 18:28 UTC
after the latest update alexa looses connection after some time. I set the refresh to 30 seconds and found related log entries in the beginning but later there are no Alexa entries anymore and Alexa cannot reach the devices any homebridge device.

**Comment by NorthernMan54** [comment] 2021-09-25 18:56
This is a duplicate of #459

**Closed by NorthernMan54** 2021-09-25 18:56 UTC
