### ISSUE TITLE
keine Thermostat anzeige

### ISSUE THREAD

**Issue by fighterzg6** [NorthernMan54/homebridge-alexa#203] opened 2019-04-11 17:21 UTC
hallo,

Alexa findet zwar alle Thermostate, und sagt mir auch die Temperatur, doch sie zeigt mir nix auf dem handy an! auch ein einstellen per spräche über den echo dot ist nicht möglich!?!?!?

**Comment by NorthernMan54** [comment] 2019-04-12 14:26
Hello,

Although Alexa finds all the thermostats, and tells me the temperature, but she shows me nothing on the phone! synonymous set by talking about the echo dot is not possible!?!?!?

Am using google translate

With my phone ( iPhone ), I can see and control the temperature.

**Comment by NorthernMan54** [comment] 2019-04-12 21:15
![IMG_3416](https://user-images.githubusercontent.com/19808920/56066688-91663800-5d46-11e9-970b-0ce3e50ce3c4.PNG)

**Comment by fighterzg6** [comment] 2019-04-12 21:18
![IMG_29DC822E85CE-1](https://user-images.githubusercontent.com/45104072/56066812-487ba700-5d79-11e9-814f-5072b72be58d.jpeg)

**Comment by fighterzg6** [comment] 2019-04-12 21:20
but it works! If I ask alexa, she tells me the right temperature and sets it on the device!

**Comment by NorthernMan54** [comment] 2019-04-13 16:31
To investigate this further I need a DEBUG log to determine what call is returning 0.  Can you collect a debug log, details here https://github.com/NorthernMan54/homebridge-alexa/blob/master/README.md#debug-logs, and share.  What I want to see in particular are the calls made when you have the App open for the thermostat

**Comment by cybersi** [comment] 2019-04-15 03:03
Hi, I am experiencing the same issue. Setting/Viewing thermostat data works through Echo, but not though the IOS App. Thank you for your help.  Here is the debug log, when opening the thermostat in the App:

 alexaLocal Emitting Alexa +13s
  EventedHTTPServer [::ffff:192.168.7.100] New connection from client +13s
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 40921 +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=13.12,13.13 +2ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=13.12,13.13 +1ms
  Accessory [Test] Getting value for Characteristic "Current Temperature" +0ms
  Accessory [Test] Getting value for Characteristic "Target Temperature" +0ms
[2019-4-15 04:46:46] [Livingroom Temperature] [*] currentTemperature: 22.2
  Accessory [Test] Got Characteristic "Current Temperature" value: 22.2 +341ms
[2019-4-15 04:46:46] [Livingroom Temperature] [*] targetTemperature: 20
  Accessory [Test] Got Characteristic "Target Temperature" value: 20 +78ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +2ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +1ms
  alexaLocal Emitting Alexa +3s
  EventedHTTPServer [::ffff:192.168.7.100] New connection from client +3s
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 38469 +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=13.12,13.13 +3ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=13.12,13.13 +0ms
  Accessory [Test] Getting value for Characteristic "Current Temperature" +3ms
  Accessory [Test] Getting value for Characteristic "Target Temperature" +0ms
  alexaLocal Emitting Alexa +208ms
  EventedHTTPServer [::ffff:192.168.7.100] New connection from client +202ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 43207 +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=3.10 +4ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=3.10 +0ms
  Accessory [Test] Getting value for Characteristic "On" +1ms
  alexaLocal Emitting Alexa +111ms
[2019-4-15 04:46:49] [Livingroom Temperature] [*] currentTemperature: 22.2
  Accessory [Test] Got Characteristic "Current Temperature" value: 22.2 +107ms
  EventedHTTPServer [::ffff:192.168.7.100] New connection from client +1ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 35151 +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=2.10 +3ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=2.10 +1ms
  Accessory [Test] Getting value for Characteristic "On" +1ms
  alexaLocal Emitting Alexa +11ms
  EventedHTTPServer [::ffff:192.168.7.100] New connection from client +4ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 43209 +1ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=4.10 +1ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=4.10 +1ms
  Accessory [Test] Getting value for Characteristic "On" +0ms
[2019-4-15 04:46:49] [Livingroom Temperature] [*] targetTemperature: 20
  Accessory [Test] Got Characteristic "Target Temperature" value: 20 +82ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +3ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +0ms
  Accessory [Test] Got Characteristic "On" value: false +9ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +6ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +0ms
  Accessory [Test] Got Characteristic "On" value: false +14ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +3ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +0ms
ERROR: alexaStateResponse ESOCKETTIMEDOUT
  EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +7s
  EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +1ms
  Accessory [Test] Got Characteristic "On" value: false +3s
  EventedHTTPServer [::ffff:192.168.7.191] Client connection closed +3m
  EventedHTTPServer [::ffff:192.168.7.191] HTTP connection was closed +0ms
  EventedHTTPServer [::ffff:192.168.7.191] HTTP server was closed +0ms

**Comment by cybersi** [comment] 2019-04-15 03:46
It seems the problem is with the "On" Characteristic. When making request through the Echo, it doesn't ask for it and it works.

**Comment by NorthernMan54** [comment] 2019-04-15 11:29
I’m going to increase the debugging output in this area, as it looks normal and nothing is jumping out at me.  Expect a new version shortly.

**Comment by cybersi** [comment] 2019-04-15 11:36
> I’m going to increase the debugging output in this area, as it looks normal and nothing is jumping out at me. Expect a new version shortly.

Great! Thanks alot!

Since this morning I am seeing different behaviour. I am getting Waiting message and three dots... and this in the logs:

EventedHTTPServer [::ffff:192.168.7.100] New connection from client +3s
  EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 38707 +0ms
  EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=13.12,13.undefined +1ms
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=13.12,13.undefined +1ms
  Accessory [Test] Getting value for Characteristic "Current Temperature" +0ms
  Accessory [Test] Could not find a Characteristic with iid of 13 and aid of NaN +0ms
[2019-4-15 13:31:35] [Livingroom Temperature] [*] currentTemperature: 22.7
  Accessory [Test] Got Characteristic "Current Temperature" value: 22.7 +311ms
  EventedHTTPServer [::ffff:172.18.95.100] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:172.18.95.100] Client connection closed +3ms
  EventedHTTPServer [::ffff:172.18.95.100] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:172.18.95.100] HTTP server was closed +0ms
  alexaLocal Emitting Alexa +3s

**Comment by cybersi** [comment] 2019-04-15 11:39
> I’m going to increase the debugging output in this area, as it looks normal and nothing is jumping out at me. Expect a new version shortly.

Great! Thank you! :)

Since this morning I am seeing different behaviour. I am getting Waiting message with three dots and this in the logs:

EventedHTTPServer [::ffff:192.168.7.100] New connection from client +3s
EventedHTTPServer [::ffff:192.168.7.100] HTTP server listening on port 38707 +0ms
EventedHTTPServer [::ffff:192.168.7.100] HTTP request: /characteristics?id=13.12,13.undefined +1ms
HAPServer [CC:22:3D:E3:CE:32] HAP Request: GET /characteristics?id=13.12,13.undefined +1ms
Accessory [Test] Getting value for Characteristic "Current Temperature" +0ms
Accessory [Test] Could not find a Characteristic with iid of 13 and aid of NaN +0ms
[2019-4-15 13:31:35] [Livingroom Temperature] [*] currentTemperature: 22.7
Accessory [Test] Got Characteristic "Current Temperature" value: 22.7 +311ms
EventedHTTPServer [::ffff:192.168.7.100] HTTP Response is finished +0ms
EventedHTTPServer [::ffff:192.168.7.100] Client connection closed +3ms
EventedHTTPServer [::ffff:192.168.7.100] HTTP connection was closed +1ms
EventedHTTPServer [::ffff:192.168.7.100] HTTP server was closed +0ms
alexaLocal Emitting Alexa +3s

**Comment by NorthernMan54** [comment] 2019-04-15 12:11
The undefined bit is concerning.  Give me about 12 hours for a a debugging release ( have to work ), and can you share your homebridge.ca logon. Want to look at the logs there

**Comment by cybersi** [comment] 2019-04-15 12:22
> The undefined bit is concerning. Give me about 12 hours for a a debugging release ( have to work ), and can you share your homebridge.ca logon. Want to look at the logs there

Sure, take your time. My homebridge.ca logon is Situla1702. Thanks. :)

**Comment by NorthernMan54** [comment] 2019-04-15 17:41
Tks this makes it easier

**Comment by NorthernMan54** [comment] 2019-04-15 23:59
Just looking at this, found the issue and it is going to be a few days.  Stay tuned

**Comment by cybersi** [comment] 2019-04-16 00:29
> Just looking at this, found the issue and it is going to be a few days. Stay tuned
> […](#)

Great! Thank you! :)

**Comment by NorthernMan54** [comment] 2019-04-24 02:10
@cybersi @fighterzg6 Please upgrade to the latest version, 0.4.12, it should resolve this issue.

**Comment by cybersi** [comment] 2019-04-24 05:26
Thank you so much. You fixed it. At first it didn't work, then I deleted one of the thermostats, removed the accessories folder, reinstalled the skill and did a search for new devices. Would love to give you a small donation for your hard work. Thank you again!

**Comment by NorthernMan54** [comment] 2019-04-24 12:02
Tks for the update, closing this

Re donations - this is something I keep thinking about, but at this time it isn’t something I’m setup to accept.  Tks for the thought though

**Closed by NorthernMan54** 2019-04-24 12:02 UTC
