### ISSUE TITLE
TV stops responding after homebridge restart

### ISSUE THREAD

**Issue by Zaphor88** [NorthernMan54/homebridge-alexa#287] opened 2020-01-04 13:50 UTC
After restarting homebridge, the television (homebridge-samsung-tizen) no longer responds via Alexa and in the Alexa app.  the television must then be deleted and added again.  the TV then reacts again via Alexa but is still reported in red with "is not responding".
![881686C6-B5EE-4ED6-AB09-99F92F4279EF](https://user-images.githubusercontent.com/49696562/71766569-8a4d0e80-2f01-11ea-8980-307e347c34c4.jpeg)

**Comment by NorthernMan54** [comment] 2020-01-04 14:23
If you ask Alexa to discover devices again, does it resolve the issue?

**Comment by Zaphor88** [comment] 2020-01-04 14:36
no Alexa does not find any new devices.  I have to delete the TV in the Alexa app first.  then Alexa finds the device again.  but it is still marked red like in the picture above.

**Comment by NorthernMan54** [comment] 2020-01-04 14:40
When you do a discover devices, it resets the internal token between Alexa and Homebridge.  Alexa will say no new devices, but the token is refreshed.  You should not need to delete and add the device again.

If the issue persists, please share a log fragment while in DEBUG mode while looking at the TV in the Alexa app.  It should show an error of some type.

**Comment by Zaphor88** [comment] 2020-01-04 14:52
OK sorry.  it works.  it doesn't recognize new devices but it works again.

can I automate the detection?

**Comment by NorthernMan54** [comment] 2020-01-04 14:56
Alexa does discovery about every 12-24 hours on her own.  If your impatient you need to ask her to do device discovery again

For this issue, it is something I’m looking into as I know what the cause is ( port number changing for published accessories ), just need to find a solution that doesn’t break it for everyone.

I’m keep this open until I have a permanent fix

**Comment by Zaphor88** [comment] 2020-01-04 14:59
great thank you very much.  and thanks for the quick help.

**Comment by mrgingles** [comment] 2020-02-17 19:24
Hi! Do you have any news about this issue? I’m having the same problem

**Comment by NorthernMan54** [comment] 2020-02-19 01:27
Still on the backlog

**Comment by Andyfad68** [comment] 2020-03-28 14:29
Hi, any news on this issue, I have the same problem. My findings:
After restart of homebridge service homebridge-alexa sends the commands to a unknown port and is refused.

homebridge[26907]: [3/26/2020, 17:34:51] [Alexa] PowerController TurnOn x.x.x.x 33129 undefined Error: connect ECONNREFUSED x.x.x.x:33129
homebridge[26907]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
homebridge[26907]:   errno: 'ECONNREFUSED',
homebridge[26907]:   code: 'ECONNREFUSED',
homebridge[26907]:   syscall: 'connect',
homebridge[26907]:   address: 'x.x.x.x',
homebridge[26907]:   port: 33129,
homebridge[26907]:   attempts: 1
homebridge[26907]: }
homebridge[26907]: ERROR: alexaStateResponse connect ECONNREFUSED x.x.x.x:33129

netstat -plutn shows nothing listening on port 33129
x.x.x.x = LAN IPv4 address of the Raspberry Pi running homebridge

and this is how it looks when everything works:

[Alexa] PowerController TurnOn x.x.x.x 44001 { characteristics: [ { aid: 1, iid: 47, status: 0 } ] } null

netstat -plutn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::44001                :::*                    LISTEN      -
tcp6       0      0 :::51826                :::*                    LISTEN      -

Maybe this help.
(I have no idea why IPv6 is used and why it is working)

Linux 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
Node.js Version v12.16.1
Npm Version v6.14.3 
homebridge-alexa v0.4.58, node v12.16.1, 
homebridge v0.4.53
Homebridge is running on port 51826
Plugins: Tizen, Hue, Alexa
TV: Samsung UE65K

Please help me!
Thank you

**Comment by NorthernMan54** [comment] 2020-05-01 01:24
Beta testing of a fix for this is available, please see issue #327

**Comment by mtressl** [comment] 2020-06-21 09:53
Will you release this soon or does it make sense to use the Beta? Saw you reopened the other issue 4 days ago.
Looking for a fix for the "TV stops responding" issue mentioned here.

**Comment by NorthernMan54** [comment] 2020-06-21 12:16
I do have a couple more items in the backlog for the beta so if this as issue for you, please try out the beta

**Comment by thehauntedmattress** [comment] 2020-09-15 12:08
Hey I was having the same issue but found the solution over at [https://github.com/tavicu/homebridge-samsung-tizen/issues/210](Homebridge-Samsung-Tizen).  Simply add: 

`    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."`

to the top of your config, and then every time Homebridge is restarted, the TV should default to the same port every time.

@NorthernMan54 may I suggest you add this to your readme so that people who use Homebridge-Alexa and Homebridge-Samsung-Tizen at the same time are aware to do this?

**Comment by NorthernMan54** [comment] 2020-10-04 15:24
@thehauntedmattress Closing this as the new version of the plugin resolves this issue.

**Closed by NorthernMan54** 2020-10-04 15:24 UTC
