### ISSUE TITLE
ERROR: alexaStateResponse connect ECONNREFUSED

### ISSUE THREAD

**Issue by Zaphor88** [NorthernMan54/homebridge-alexa#318] opened 2020-04-14 20:50 UTC
I keep getting the message:

ERROR: alexaStateResponse connect ECONNREFUSED 192.168.178.20:41047

(192.168.178.20) is the network ip of the Raspberry with Homebridge.

how can I find out what that is. I can not find anything that runs on port 41047.

**Comment by NorthernMan54** [comment] 2020-04-14 21:45
I was likely a camera or TV, they use dynamic ports.  Restarting the plugin and asking Alexa to discover devices will refresh the mapping.

**Comment by Zaphor88** [comment] 2020-04-14 22:51
OK.  I don't have a camera and a TV that is supposed to run on homebridge-samsung-tizen on port 45111.
but the TV is also constantly displayed as a device not responding.
Server restart and device search has already been carried out several times for other reasons.  the message is still coming.

**Comment by NorthernMan54** [comment] 2020-04-14 23:04
Your discovery response at Apr 14 19:04:13 had this

"friendlyName":"Fernseher","description":"Fernseher Fernseher Television","manufacturerName":"Samsung TV"

ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.178.20\",\"port\":41047,\"aid\":1,\"iid\":10}

And at Apr 14 22:56:42 it had this

"friendlyName":"Fernseher","description":"Fernseher Fernseher Television","manufacturerName":"Samsung TV"

"ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.178.20\",\"port\":45181,\"aid\":1,\"iid\":10}

Timing is important

PS This is a duplicate of #287

**Comment by Zaphor88** [comment] 2020-04-15 04:31
OK.  so that's the same mistake.  and I have to wait until you find the bug? 
thanks for the help and i'm sorry for the double post.

**Comment by NorthernMan54** [comment] 2020-04-16 01:10
I'm just glad its an existing issue and not a new one.

Tks

**Closed by NorthernMan54** 2020-04-16 01:10 UTC
