### ISSUE TITLE
Duplicates devices keep popping up

### ISSUE THREAD

**Issue by mreassassin** [NorthernMan54/homebridge-alexa#361] opened 2020-09-15 16:11 UTC
Every hour or so I'm noticing all of my homebridge devices being discovered a 2nd time in Alexa.  It only happens a 2nd time. If I delete just a couple of those dupes only those that I depleted come back in about an hour. I've limited the Alexa plugin to just one instance of HB. It's the only instance I have running. 

Any ideas?  I've deleted all and recreated all my routines a couple times already. My next step is do disable all 125 dupes. Why did this just start happening a few weeks ago?

`        {
            "name": "Alexa",
            "username": "mreassassin",
            "password": "xxxxxx",
            "pin": "xxx-xx-xxx",
            "routines": true,
            "debug": false,
            "refresh": 900,
            "filter": "192.168.1.22:51826",
            "platform": "Alexa"
        }, `

**Comment by NorthernMan54** [comment] 2020-09-15 16:29
What version of homebridge are you running?  The latest beta will trigger this behaviour.  The only real fix is to delete all the homebridge devices in Alexa and discover them again.

Unfortunately this will break all room placements and routines

**Comment by mreassassin** [comment] 2020-09-15 16:45
1.2.1
that does kinda add up as I was on the beta about a month ago.  I've since upgraded to the latest release (1.2.1 was just installed today) and have already deleted all and rediscovered all through alexa and the dupes still came back this morning.

Is there a cache that could be cleared?

**Comment by NorthernMan54** [comment] 2020-09-15 16:54
After dealing with it a few weeks and discussing the issues with the homebridge development team, I ended up deleting all my devices via the amazon Alexa web site. And discovering again

**Comment by mreassassin** [comment] 2020-09-15 16:56
hmmmmmmm....   that's exactly what I did a few days ago.  I'm gonna try again.  thanks!

**Comment by neo3** [comment] 2020-09-16 21:08
I'm having the same problem, any solution?

**Comment by NorthernMan54** [comment] 2020-09-16 21:31
Unfortunately no. You will need to delete all you devices from the Amazon app or Website and discover them again.  Unfortunately this will break any room placements or routines that you have, so you may want to record them before deleting.

This is caused by the latest version of Homebridge

**Comment by mreassassin** [comment] 2020-09-16 22:15
Yesterday I had an update for homebridge. Just after updating I deleted all devices and rediscovered. No dupes since...  but I haven't been home very much today so I'm hoping when I do get home the dupes don't show up. Not sure if being home on my home network matters or not since homebridge and Alexa are both still running while I'm not there. Will report back tomorrow.

**Comment by Silas888** [comment] 2020-09-18 16:41
Forgive me but I can't believe that the solution is to delete all of the devices and add them again! I have hundreds of items and 40 or so routines. Moreover how do we know if we make this change, Homebridge won't make another update which will require us to do this all over again? How can there not be a programmatic way to resolve this?!

**Comment by NorthernMan54** [comment] 2020-09-18 20:57
@Silas888 I feel your pain as I also have a lot of devices, and went thru this a few weeks ago with the beta stream.  When discussing with the homebridge team, this was needed to fix the random ‘not responding’ issues people have been suffering with.

**Comment by neo3** [comment] 2020-09-19 11:41
I have my homebridge updated and after removing all devices and searching again, today Alexa duplicate the devices of the webOS TV again.

**Comment by mreassassin** [comment] 2020-09-19 14:53
Try unlinking your homebridge skill in Alexa and then delete all devices from Alexa. Then re link and re discover. That's what I did and no dupes have come back since.

**Comment by Pblondin123** [comment] 2020-09-19 18:30
i have 52 devices to delete and relink :-(

**Comment by neo3** [comment] 2020-09-23 22:20
> Try unlinking your homebridge skill in Alexa and then delete all devices from Alexa. Then re link and re discover. That's what I did and no dupes have come back since.

I tried this, but my TV's controls with the homebridge-webos-tv plugin still keep duplicating.

**Comment by NorthernMan54** [comment] 2020-09-24 03:06
Can you share an accessory dump from that plugin?  I’m wonder if it’s the plugin possibly

**Comment by Pblondin123** [comment] 2020-09-24 10:03
fyi on my side the dupes are caused by the DummySwitch plugin (1 lightbulb and 1 contact sensor gets generated for each entry from DummySwitch in Alexa).  i end up with this in the HB log: [9/24/2020, 5:46:15 AM] [Alexa] WARNING: Duplicate device name xxxxx.   My automations seems all working fine since i deleted recreated the devices.

**Comment by NorthernMan54** [comment] 2020-09-24 22:46
The duplicate device message is just letting you know that you have two devices with the same name.  Which will call issues with Alexa when you attempt to control them

**Comment by neo3** [comment] 2020-09-25 22:55
> Can you share an accessory dump from that plugin? I’m wonder if it’s the plugin possibly

[2020-9-25 11:47:26] [webostv] [TV do Quarto] Connected to TV
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Got TV information
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV webOS version: 3.5
[2020-9-25 11:47:27] [webostv] [TV do Quarto] App launched, current appId: com.webos.app.miracast
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV turned on!
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Sound output changed. Current sound output: tv_speaker
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Subscribed to TV services
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Connected to remote pointer input socket
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Setup finished
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV setup finished, ready to control tv
[2020-9-25 11:47:44] [Alexa] alexaDiscovery - returned 40 devices

config.json:

`{
            "devices": [
                {
                    "name": "TV do Quarto",
                    "ip": "192.168.1.112",
                    "mac": "XX-XX-XX-XX-XX-XX",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "mediaControl": true,
                    "appButtons": [
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube no Quarto"
                        }
                    ],
                    "remoteSequenceButtons": [
                        {
                            "sequence": [
                                "HOME",
                                "LEFT",
                                "ENTER"
                            ],
                            "name": "Canais Online"
                        },
                        {
                            "sequence": [
                                "DOWN",
                                "ENTER"
                            ],
                            "name": "Canal"
                        },
                        {
                            "sequence": [
                                "HOME",
                                "ENTER"
                            ],
                            "name": "Amazon Prime no Quarto"
                        },
                        {
                            "sequence": [
                                "HOME",
                                "RIGHT",
                                "ENTER"
                            ],
                            "name": "Compartilhamento de Tela"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        },`

**Comment by NorthernMan54** [comment] 2020-09-26 12:45
This is how to collect a Homebridge accessory dump

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by neo3** [comment] 2020-09-26 14:58
> This is how to collect a Homebridge accessory dump
> 
> https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump


[accessories.txt](https://github.com/NorthernMan54/homebridge-alexa/files/5286847/accessories.txt)

**Comment by NorthernMan54** [comment] 2020-09-28 16:08
@neo3 Unfortunately that wasn't the WebOS TV Plugin.   The TV Plugins are using a separate port within Homebridge, that changes with every restart of Homebridge.  You would need to collect the port number during the startup of homebridge, then run the accessory dump against that port number.

**Comment by neo3** [comment] 2020-09-28 23:15
The port changes between the values ​​of 40.000:
[tv.txt](https://github.com/NorthernMan54/homebridge-alexa/files/5295514/tv.txt)

**Comment by NorthernMan54** [comment] 2020-09-29 03:19
I believe this issue with TV accessories was fixed in the BETA version a while back, please update to the beta.

**Comment by neo3** [comment] 2020-09-29 14:21
> I believe this issue with TV accessories was fixed in the BETA version a while back, please update to the beta.

How do I install the Beta version?

**Comment by NorthernMan54** [comment] 2020-09-29 18:55
Please see issue #327 

I believe this is a duplicate of this #287

**Comment by neo3** [comment] 2020-10-01 20:37
It's still duplicating when Homebridge restarts or I turn my TV off and on again.
![Alexa](https://user-images.githubusercontent.com/1847148/94860561-a0deb280-040c-11eb-9b89-367c4b56e194.png)
![WhatsApp Image 2020-10-01 at 17 32 03](https://user-images.githubusercontent.com/1847148/94860620-b5bb4600-040c-11eb-8758-b4249f3554bc.jpeg)

**Comment by NorthernMan54** [comment] 2020-10-02 23:25
I'm going to look at the logs on the backend for this.

Can you share your id on the homebridge.ca cloud, and ask Alexa to discover devices and let me know the approx time in GMT when you ask her ( so I can find it in the logs ).  Then cause the issue to re-occur, and ask Alexa to discover devices again, and let me know that time in GMT.

Tks

**Comment by neo3** [comment] 2020-10-03 16:16
> discover devices

I deleted all my devices today and did the devices search at 4:03pm, then I ran a second search and Alexa didn't find any new devices. After I restarted my homebridge and at 4:06 pm I did the third devices search where Alexa duplicated the devices of the TV.

> I'm going to look at the logs on the backend for this.
> 
> Can you share your id on the homebridge.ca cloud, and ask Alexa to discover devices and let me know the approx time in GMT when you ask her ( so I can find it in the logs ). Then cause the issue to re-occur, and ask Alexa to discover devices again, and let me know that time in GMT.
> 
> Tks

I deleted all my devices today and did the devices search at 4:03pm, then I ran a second search and Alexa didn't find any new devices. After I restarted my homebridge and at 4:06 pm I did the third devices search where Alexa duplicated the devices of the TV. 

My id is "afcneo", when you see this my post please delete it for security.

**Comment by NorthernMan54** [comment] 2020-10-03 16:25
Removed

**Comment by neo3** [comment] 2020-10-03 16:27
> Removed

Thanks!

**Comment by NorthernMan54** [comment] 2020-10-03 20:48
Do you know what version of homebridge your running?

**Comment by neo3** [comment] 2020-10-03 20:53
> Do you know what version of homebridge your running?
> […](#)
> Sent from my iPad
> On Oct 3, 2020, at 12:27 PM, neo3 ***@***.***> wrote: ﻿ Removed Thanks! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Version 1.2.3

**Comment by NorthernMan54** [comment] 2020-10-04 14:12
@neo3 Does it ever have more than 2 - 3 duplicates of the accessory/device?

Looking at the logs captured yesterday, the unique id for your TV is changing values based on information from the WebOS TV Plugin

"normal": "2A:D5:E8:02:2A:98-Unknown-**LG Electronics**-TV do Quarto-000000D8-0000-1000-8000-0026BB765291"

"normal": "2A:D5:E8:02:2A:98-Unknown-**Unknown**-TV do Quarto-000000D8-0000-1000-8000-0026BB765291"

The value 'LG Electronics' switching to 'Unknown' is triggering the issue

And looking at the webos tv plugin, I believe this line is triggering the issue

https://github.com/merdok/homebridge-webos-tv/blob/9be825e57e313a7966ac814f00ff3ad331682d8f/index.js#L249

@merdok I'm wondering why you are removing the information service here, and not just updating the values within the information service?  It looks like the remove is causing a bit of a race condition with the publishing of the accessory on startup.

The two unknown values in the log fragment are mapped to the 'Model' and 'Manufacturer' field in the information service.  The first unknown 'Model' is read from the mdns/bonjour HAP discovery message ( and is populated from the information service by HAP-NodeJS ), and the second 'manufacturer' is read from the information service during the instance discovery
phase.

**Comment by merdok** [comment] 2020-10-04 16:18
@NorthernMan54 you cannot update the information. This is a limitation of HomeKit. So in order for me to update the information services, it needs to be re-added to the accessory after the information has been retrieved from the device.

**Comment by neo3** [comment] 2020-10-04 19:11
> @neo3 Does it ever have more than 2 - 3 duplicates of the accessory/device?

I usually delete the copy after it duplicates, because the command I use stops working.

Now I installed the new update that you made available and saw that the TV is still duplicating, but now I have inactivated the duplicated device on Alexa and I'm doing some tests to see if a third TV device appears.

**Comment by NorthernMan54** [comment] 2020-10-05 00:53
@merdok Have you tried updatePlatformAccessories ?  I have been using this with my latest platform plugin and it seems to work pretty good for updating of values.

https://github.com/NorthernMan54/homebridge-tasmota/blob/05c524281242c78a49c97f07ca5f35e161410e67/src/platform.ts#L206

**Comment by merdok** [comment] 2020-10-05 06:26
@NorthernMan54 
this is not about updating values itself, it is about the accessory information service which is in some way special and it's values cannot be changed anymore after it has been registered on the accessory. The only way as far as I know to do updates on the fly on that service is to remove and re-add it. 
I think that you should somehow handle that case since there can only be one information service on an accessory, so any changes to that means that there was just an update and no new Alexa device needs to be created.

**Comment by DJBenson** [comment] 2020-10-06 15:35
So the latest update (and I understand the reason, but just trying to fix it) completely broke my install.

I've deleted and attempted a re-discover of devices but despite homebridge-alexa showing a discovery log, the devices never end up in Alexa. I've unlinked/removed the skill, deleted all devices and linked again, the homebridge.ca website shows active connections (i.e. the dates are recent) but still no devices in the Alexa app or the portal.

`[10/6/2020, 4:33:08 PM] [Alexa] alexaDiscovery - returned 119 devices`

![image](https://user-images.githubusercontent.com/1013909/95223654-c0515300-07f1-11eb-8679-7fc00ffa71bb.png)

![image](https://user-images.githubusercontent.com/1013909/95223742-d3642300-07f1-11eb-8d9c-8775f4ccc450.png)

Any idea's?

**Comment by NorthernMan54** [comment] 2020-10-06 19:22
@DJBenson can you share your homebridge.ca id I want to check the backend logs.  Also have you asked Alexa to discover devices

**Comment by DJBenson** [comment] 2020-10-07 00:38
> @DJBenson can you share your homebridge.ca id I want to check the backend logs. Also have you asked Alexa to discover devices

Yes - it doesn't matter if I start the discovery from an Echo device, the app or the Alexa portal, the scan hits Homebridge (shown above with the 119 devices discovered) but the devices never seemingly get handed back to Alexa.

My ID is the same as my GitHub username.

**Comment by NorthernMan54** [comment] 2020-10-07 16:11
@DJBenson Am looking at the logs and can see the request being passed to Amazon.  And was looking at the data quickly and am thinking these device's are causing Amazon to choke on the data.  And in particular the input options.

```
               "friendlyName": "Move TV",
               "description": "Move (S17) Move TV Television",
               "manufacturerName": "Sonos",
               "displayCategories": ["TV"],

               "friendlyName": "Kitchen TV",
               "description": "Connect:Amp (ZP120) Kitchen TV Television",
               "manufacturerName": "Sonos",
               "displayCategories": ["TV"],
```

Can you supply a Homebridge accessory dump from that instance of homebridge?

**Comment by DJBenson** [comment] 2020-10-07 16:17
> @DJBenson Am looking at the logs and can see the request being passed to Amazon. And was looking at the data quickly and am thinking these device's are causing Amazon to choke on the data. And in particular the input options.
> 
> ```
>                "friendlyName": "Move TV",
>                "description": "Move (S17) Move TV Television",
>                "manufacturerName": "Sonos",
>                "displayCategories": ["TV"],
> 
>                "friendlyName": "Kitchen TV",
>                "description": "Connect:Amp (ZP120) Kitchen TV Television",
>                "manufacturerName": "Sonos",
>                "displayCategories": ["TV"],
> ```
> 
> Can you supply a Homebridge accessory dump from that instance of homebridge?

Really weird unless the homebridge-zp plug-in changed something recently. I will try disabling that plugin for now and see how far I get. Thanks for those pointers. If I don't have any luck I’ll send a homebridge dump.

**Comment by NorthernMan54** [comment] 2020-10-07 16:21
This is likely on my side, as with the new version I added support for input control, and the input data looked wacky.  I likely need to sanitize the data fields

**Comment by DJBenson** [comment] 2020-10-07 16:22
> This is likely on my side, as with the new version I added support for input control, and the input data looked wacky. I likely need to sanitize the data fields

I’ll provide a dump as soon as get a moment.

**Comment by DJBenson** [comment] 2020-10-07 17:29
@NorthernMan54 I'm getting a 500 error when using that curl command against any of my Homebridge instances (I have 6 "production" instances and one "test" instance).

Should it work out of the box?

**Comment by NorthernMan54** [comment] 2020-10-07 17:37
Yes, I use it all the time. Do you have correct port?

**Comment by NorthernMan54** [comment] 2020-10-07 17:42
Have confirmed it is those two devices. I uploaded your discovery object to my test Alexa instance minus those two and I got 117 devices. Now looking at the data for those two in detail

**Comment by DJBenson** [comment] 2020-10-07 17:43
Yes, I've tried it both outside of the docker container (using the host IP) and inside the container (using the loopback address) and it returns the same error for all 7 instances.

**Comment by NorthernMan54** [comment] 2020-10-07 18:03
Found the issue

Take a look at the cookie section in this article

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery-objects.html

Your cookie object is 10K .... versus 5K max for those two devices.  If I manually remove all the "Input ##" it works.

```
"cookie": {
          "TurnOn": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":10,\"value\":1}",
          "TurnOff": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":10,\"value\":0}",
          "Active Identifier": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":11}",
          "Pause": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":13,\"value\":11}",
          "Play": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":13,\"value\":8}",
          "Stop": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":13,\"value\":9}",
          "Next": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":13,\"value\":7}",
          "Previous": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":13,\"value\":6}",
          "ReportState": "[{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":10},{\"interface\":\"Alexa.StepSpeaker\",\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":21}]",
          "AdjustVolume": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"iid\":21}",
          "n/a": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":1,\"iid\":11}",
          "AirPlay": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":2,\"iid\":11}",
          "Audio In": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":3,\"iid\":11}",
          "TV": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":4,\"iid\":11}",
          "Ballerina (Original Motion Picture Soundtrack)": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":5,\"iid\":11}",
          "Dance": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":6,\"iid\":11}",
          "Folders": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":7,\"iid\":11}",
          "Frozen (Original Motion Picture Soundtrack)": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":8,\"iid\":11}",
          "Lilo & Stitch (Original Motion Picture Soundtrack)": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":9,\"iid\":11}",
          "Lullaby Versions of Disney Classics": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":10,\"iid\":11}",
          "Lullaby Versions of Frozen": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":11,\"iid\":11}",
          "Lullaby Versions of Oasis": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":12,\"iid\":11}",
          "My Little Pony: The Movie (Original Motion Picture Soundtrack)": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":13,\"iid\":11}",
          "Rather Be": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":14,\"iid\":11}",
          "Trolls (Original Motion Picture Soundtrack)": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":15,\"iid\":11}",
          "Input 16": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":16,\"iid\":11}",
          "Input 17": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":17,\"iid\":11}",
          "Input 18": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":18,\"iid\":11}",
          "Input 19": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":19,\"iid\":11}",
          "Input 20": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":20,\"iid\":11}",
          "Input 21": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":21,\"iid\":11}",
          "Input 22": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":22,\"iid\":11}",
          "Input 23": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":23,\"iid\":11}",
          "Input 24": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":24,\"iid\":11}",
          "Input 25": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":25,\"iid\":11}",
          "Input 26": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":26,\"iid\":11}",
          "Input 27": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":27,\"iid\":11}",
          "Input 28": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":28,\"iid\":11}",
          "Input 29": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":29,\"iid\":11}",
          "Input 30": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":30,\"iid\":11}",
          "Input 31": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":31,\"iid\":11}",
          "Input 32": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":32,\"iid\":11}",
          "Input 33": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":33,\"iid\":11}",
          "Input 34": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":34,\"iid\":11}",
          "Input 35": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":35,\"iid\":11}",
          "Input 36": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":36,\"iid\":11}",
          "Input 37": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":37,\"iid\":11}",
          "Input 38": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":38,\"iid\":11}",
          "Input 39": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":39,\"iid\":11}",
          "Input 40": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":40,\"iid\":11}",
          "Input 41": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":41,\"iid\":11}",
          "Input 42": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":42,\"iid\":11}",
          "Input 43": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":43,\"iid\":11}",
          "Input 44": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":44,\"iid\":11}",
          "Input 45": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":45,\"iid\":11}",
          "Input 46": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":46,\"iid\":11}",
          "Input 47": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":47,\"iid\":11}",
          "Input 48": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":48,\"iid\":11}",
          "Input 49": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":49,\"iid\":11}",
          "Input 50": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":50,\"iid\":11}",
          "Input 51": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":51,\"iid\":11}",
          "Input 52": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":52,\"iid\":11}",
          "Input 53": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":53,\"iid\":11}",
          "Input 54": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":54,\"iid\":11}",
          "Input 55": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":55,\"iid\":11}",
          "Input 56": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":56,\"iid\":11}",
          "Input 57": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":57,\"iid\":11}",
          "Input 58": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":58,\"iid\":11}",
          "Input 59": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":59,\"iid\":11}",
          "Input 60": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":60,\"iid\":11}",
          "Input 61": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":61,\"iid\":11}",
          "Input 62": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":62,\"iid\":11}",
          "Input 63": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":63,\"iid\":11}",
          "Input 64": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":64,\"iid\":11}",
          "Input 65": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":65,\"iid\":11}",
          "Input 66": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":66,\"iid\":11}",
          "Input 67": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":67,\"iid\":11}",
          "Input 68": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":68,\"iid\":11}",
          "Input 69": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":69,\"iid\":11}",
          "Input 70": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":70,\"iid\":11}",
          "Input 71": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":71,\"iid\":11}",
          "Input 72": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":72,\"iid\":11}",
          "Input 73": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":73,\"iid\":11}",
          "Input 74": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":74,\"iid\":11}",
          "Input 75": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":75,\"iid\":11}",
          "Input 76": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":76,\"iid\":11}",
          "Input 77": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":77,\"iid\":11}",
          "Input 78": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":78,\"iid\":11}",
          "Input 79": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":79,\"iid\":11}",
          "Input 80": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":80,\"iid\":11}",
          "Input 81": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":81,\"iid\":11}",
          "Input 82": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":82,\"iid\":11}",
          "Input 83": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":83,\"iid\":11}",
          "Input 84": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":84,\"iid\":11}",
          "Input 85": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":85,\"iid\":11}",
          "Input 86": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":86,\"iid\":11}",
          "Input 87": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":87,\"iid\":11}",
          "Input 88": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":88,\"iid\":11}",
          "Input 89": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":89,\"iid\":11}",
          "Input 90": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":90,\"iid\":11}",
          "Input 91": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":91,\"iid\":11}",
          "Input 92": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":92,\"iid\":11}",
          "Input 93": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":93,\"iid\":11}",
          "Input 94": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":94,\"iid\":11}",
          "Input 95": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":95,\"iid\":11}",
          "Sonos Chime": "{\"deviceID\":\"D8:7C:CE:DB:CC:9B\",\"aid\":1,\"value\":96,\"iid\":11}"
```

**Comment by DJBenson** [comment] 2020-10-07 18:34
@NorthernMan54 thanks for the info but I have no idea how to resolve that other than disabling the plugin - do you think it's worth mentioning it to the developer of the homebridge-zp plugin?

**Comment by NorthernMan54** [comment] 2020-10-07 18:46
If you update to the latest version, it should now automatically remove those 2 devices and you should be good to go.

I will open as issue with the dev there

**Comment by DJBenson** [comment] 2020-10-07 19:42
> If you update to the latest version, it should now automatically remove those 2 devices and you should be good to go.
> 
> I will open as issue with the dev there

Updated and the Alexa sprang back into life. Many thanks (and for opening the ticket on the homebridge-zp repo).

**Closed** 2021-03-18 02:31 UTC
