### ISSUE TITLE
Homebridge crashes in response to TV controls

### ISSUE THREAD

**Issue by mwkchan** [NorthernMan54/homebridge-alexa#310] opened 2020-04-07 09:42 UTC
Homebridge crashed after Alexa plugin tried to response to a TV control request.

ERROR: alexaStateResponse getaddrinfo ENOTFOUND undefined
[4/7/2020, 5:33:43 PM] [Alexa] Speaker-get AdjustVolume 192.168.1.11 57604 undefined Error: connect ECONNREFUSED 192.168.1.11:57604
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
 {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.11',
  port: 57604,
  attempts: 1
}
[4/7/2020, 5:33:43 PM] TypeError: Cannot read property 'characteristics' of undefined
    at alexaHome.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:546:25)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:393:7)
    at Request._callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at self.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:323:22)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[4/7/2020, 5:33:43 PM] Got SIGTERM, shutting down Homebridge...
[4/7/2020, 5:33:43 PM] [Master Room Hub] INFO - shutdown

Here's my config:

        {
            "name": "Alexa",
            "username": "...",
            "password": "...",
            "pin": "199-70-701",
            "routines": true,
            "debug": false,
            "platform": "Alexa",
            "inputs": [
                {
                    "into": "Master Room TV",
                    "devices": [
                        {
                            "manufacturer": "Harmony",
                            "name": "Live TV",
                            "alexaName": "TV TUNER"
                        },
                        {
                            "manufacturer": "Harmony",
                            "name": "Apple TV",
                            "alexaName": "APPLE TV"
                        },
                        {
                            "manufacturer": "Harmony",
                            "name": "BBC",
                            "alexaName": "TV BBC"
                        },
                        {
                            "manufacturer": "Harmony",
                            "name": "Netflix",
                            "alexaName": "TV NETFLIX"
                        },
                        {
                            "manufacturer": "Harmony",
                            "name": "my TV Super",
                            "alexaName": "MEDIA PLAYER"
                        },
                        {
                            "manufacturer": "Harmony",
                            "name": "Bluetooth Music",
                            "alexaName": "HD RADIO"
                        }
                    ]
                }
            ]
        }

**Comment by NorthernMan54** [comment] 2020-04-07 13:08
Can you share a homebridge accessory dump, details are in the README

**Comment by mwkchan** [comment] 2020-04-07 13:15
Here you are:

[accessory.dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4444514/accessory.dump.txt)

**Comment by NorthernMan54** [comment] 2020-04-08 00:42
You are having two issues here, first is a duplicate of #287.  For this you need to ask Alexa to discover devices after restarting homebridge until I can get a fix for that.

And for the Homebridge crash, I added logic to prevent crashes so this shouldn't re-occur.  So please update to the latest and try again.  If it re-occurs please share a log again.

**Closed** 2020-04-14 23:04 UTC
