### ISSUE TITLE
homebridge-alexa RangeError

### ISSUE THREAD

**Issue by jaydhary14** [NorthernMan54/homebridge-alexa#482] opened 2021-12-26 04:13 UTC
I have homebridge running as a node on MacMini (Intel) 

I am getting below error 

[12/25/2021, 10:10:33 PM] RangeError: Maximum call stack size exceeded
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:30:5)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)

**Comment by NorthernMan54** [comment] 2021-12-26 04:27
Duplicate of #481

**Closed by NorthernMan54** 2021-12-26 04:27 UTC
