### ISSUE TITLE
doorbell rings take a long time to respond

### ISSUE THREAD

**Issue by garethsnaim** [NorthernMan54/homebridge-alexa#461] opened 2021-09-01 19:41 UTC
Thank you for this plugin, I am still learning. Its up and running and really all I need is my protect G4 doorbell when pressed to be announced by my echos.
And sure enough it does, yeah. But anywhere between 5-20 seconds after the button was pressed.

Is there much I can do to chivvy it along a bit?

Homebrige is running in docker on a meaty server, network is all unifi. I have to say homekit and airplay seems to not be entirely reliable on this network so accept that may have a part to play.

**Comment by NorthernMan54** [comment] 2021-09-01 23:13
Doorbells are sent over to Alexa via an event channel and it is rate limited on the Amazon side to one event every 10 seconds.  So if another event is in the queue already or recently sent it needs to wait.  I have made doorbell events a priority, as it was previously taking almost a minute in my house, due to my motion sensors being triggered by people walking up to the doorbell.

**Comment by garethsnaim** [comment] 2021-09-02 07:33
Ah ok, thats interesting. Well I only want this whole system to get a noise from the unifi doorbell out of alexa, but what has happened is like 50 devices have been added to alexa as a result, a lot of which are cameras.
Trouble is I can remove them but if I ask alexa to find new devices they will be all added again. I will see if there is a way to manage that.
Thanks for the heads up

**Comment by garethsnaim** [comment] 2021-09-02 09:44
oh just discovered your ignore list nice!

**Comment by NorthernMan54** [comment] 2021-09-02 11:43
Pls see #458 

I’m working on this, so it should be resolved shortly

**Comment by NorthernMan54** [comment] 2021-10-05 01:16
Closing as a duplicate of #458

**Closed by NorthernMan54** 2021-10-05 01:16 UTC
