### ISSUE TITLE
New (same) devices being discover if the Pi restart and IP changed

### ISSUE THREAD

**Issue by lily148** [NorthernMan54/homebridge-alexa#152] opened 2018-12-13 02:37 UTC
Hi, I notice if I restart my Pi and assign with a new IP address, Alexa will re-create all my homebridge devices again. The old device will become unresponsive. 
I have to regroup everything and reset all the routine again.
If I set static IP then it will be okay.

**Comment by NorthernMan54** [comment] 2018-12-13 04:00
This is a duplicate of issue #97 

If the ip stays the same, she will not create duplicates

**Closed by NorthernMan54** 2018-12-13 04:00 UTC
