### ISSUE TITLE
Homebridge-dummy switch not discovered in alexa

### ISSUE THREAD

**Issue by bradc101** [NorthernMan54/homebridge-alexa#325] opened 2020-04-29 19:00 UTC
Having a rather puzzling problem. I have several homebridge-dummy switches that I use to control non-HomeKit devices. The other day, I created another dummy switch in my config, but for some reason it was not discovered in the Alexa app. Looking at the homebridge log, it appears that the device is discovered, but not accessible to the Alexa app. Very strange because I have several other switches that work fine. Tried using a different dummy plugin (homebridge-statefuldummy, but still no joy. Other dummy switches defined months ago still working fine. Looking for help debugging this issue. Thanks!

**Comment by NorthernMan54** [comment] 2020-04-29 19:10
Unless you restart the Alexa plugin there is a delay until new devices are discoverable. Typically about 30 minutes. You can then ask Alexa to discover them.

If they are still not discoverable, please a homebridge accessory dump so I can look into what’s happening.

PS I’m using homebridge-dummy and don’t have any issues

**Comment by bradc101** [comment] 2020-04-29 19:32
Ok, will provide the accessory dump later today when I can get back to it. By the way, I have been using homebridge-dummy for quite awhile. No problem until now. Thanks for your help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bradc101** [comment] 2020-04-29 22:58
Attached are my accessory dump and the config file. Really appreciate you taking the time to look at this for me. The dummy switch I am trying to add is the last one in the accessory section. Let me know if there is anything else, and thanks again!

**Comment by bradc101** [comment] 2020-04-29 23:10
Ok, sorry. I had some junk in the setup that i meant to get rid of before i sent this stuff to you. So, please use the attached files and not the ones I sent earlier. Sorry about that!

**Comment by NorthernMan54** [comment] 2020-04-30 20:40
@bradc101 Your files aren't attached

**Comment by bradc101** [comment] 2020-04-30 20:49
Damnit - Sorry. How about now?

[config.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4561106/config.txt)
[homebridge.accessory.dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4561109/homebridge.accessory.dump.txt)

**Comment by NorthernMan54** [comment] 2020-04-30 21:40
Got them

**Comment by NorthernMan54** [comment] 2020-05-01 01:03
Found the issue, your Front Door lock is what triggered it.  The plugin was not returning a blank value in the manufacturer field, which Amazon didn't like.  Do you know what plugin your front door comes from?

Please update to the latest version and you should be fine.

**Comment by bradc101** [comment] 2020-05-01 02:47
Thanks you. The update you pushed out worked. The front door uses the Wink plugin. Thanks again for your help and speedy reply!

**Comment by bradc101** [comment] 2020-05-01 03:23
Well, got excited too quickly. Once I restarted my homebridge, got the following error:

[4/30/2020, 8:11:33 PM] [HarmonyHub] (HarmonyHub)INFO - configuring Main TV Service
[4/30/2020, 8:11:33 PM] [HarmonyHub] (HarmonyHub)INFO - Configuring Main Activity Watch TV
[4/30/2020, 8:11:33 PM] [HarmonyHub] (HarmonyHub)INFO - Loading general volume Slider...
[4/30/2020, 8:11:35 PM] [Config] Homebridge Config UI X v4.17.1 is listening on :: port 8080
[4/30/2020, 8:11:51 PM] [Alexa] ERROR: HAP Discovery failed, please review config

Removed the wink3 plugin, but still the same error. So, as of now, none of my dummy switches are working. Sorry to bug you again. Attached a new accessory dump just in case you need it.

[homebridge.accessory.dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4562386/homebridge.accessory.dump.txt)

**Comment by NorthernMan54** [comment] 2020-05-01 11:34
Any errors from the Alexa plugin from earlier in the log?

Dump looks okay

**Comment by bradc101** [comment] 2020-05-01 16:14
I have attached part of the log file from right after a restart. Don't see anything that looks like an error. Let me know if there is anything else I can do to help. Thanks.

[Homebridge Log.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4565148/Homebridge.Log.txt)

**Comment by NorthernMan54** [comment] 2020-05-01 16:42
If you can start homebridge in DEBUG mode it includes a lot more debugging data, can you share a log with DEBUG enabled.

**Comment by bradc101** [comment] 2020-05-01 18:35
Here is the log with debug enabled. Hope I did this correctly. Thanks again!
[Homebridge Debug.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4565808/Homebridge.Debug.txt)

**Comment by bradc101** [comment] 2020-05-01 18:48
Not sure if this is helpful or not. Attached log with debug turned in with homebridge-config plugin. Anyway, here you go.

[Homebridge-config debug.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4565858/Homebridge-config.debug.txt)

**Comment by NorthernMan54** [comment] 2020-05-02 12:56
@bradc101 I added more debugging for the issue.  Can you update and try again.

For logs, your first attempt included the details needed.  Can you share one that way again

**Comment by bradc101** [comment] 2020-05-02 18:35
Ok, here is the debug log. Thanks again for your help with this.
[debug_logfile.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4568535/debug_logfile.txt)

**Comment by NorthernMan54** [comment] 2020-05-02 18:53
Thanks for that log, the problem is here

```
2020-05-02T18:24:37.979Z hapNodeJSClient HAP Device discovered Homebridge 5E53
2020-05-02T18:24:37.980Z hapNodeJSClient HAP Device address Homebridge 5E53 ->  { host: undefined,
  port: 51826,
  url: undefined,
  deviceID: 'CC:22:3D:E3:CE:40',
  txt:
   { md: 'Homebridge',
     pv: '1.1',
     id: 'CC:22:3D:E3:CE:40',
     'c#': '32',
     's#': '1',
     ff: '0',
     ci: '2',
     sf: '0',
     sh: 'nu8WVA==' } }
2020-05-02T18:24:37.981Z hapNodeJSClient HAP Discover failed Homebridge -> undefined error Error: Invalid URI "undefined/accessories"
```

undefined should be the IP address of your homebridge instance

What version of homebridge are you running ?  Is is the latest 1.0.4 ?

Could you install this package and share the output

https://github.com/homebridge/mdns-diagnostics

**Comment by bradc101** [comment] 2020-05-02 20:45
I am running 1.0.4 of Homebridge. Here is the output from mdns-diagnostics:

Mac-mini-3:.homebridge Brad$ mdns-diagnostics
Basestation, VMB4000,  192.168.1.15:35505
iHome SmartPlug-76D2B5, iSP6X,  192.168.1.55:80
iHome SmartPlug-76D2B5, iSP6X,  fe80::82c5:f2ff:fe76:d2b5:80
iHome SmartPlug-18E078, iSP6X,  192.168.1.90:80
iHome SmartPlug-18E078, iSP6X,  fe80::429f:38ff:fe18:e078:80
iHome SmartPlug-398D6C, iSP8,  192.168.1.64:80
iHome SmartPlug-398D6C, iSP8,  fe80::82a5:89ff:fe39:8d6c:80
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  192.168.1.23:80
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  fe80::207:a6ff:fe0c:f5bb:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  192.168.1.173:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  fe80::207:a6ff:fe07:86ee:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  192.168.1.169:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  fe80::e623:54ff:fe0c:2f1c:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  192.168.1.235:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  fe80::207:a6ff:fe0a:feff:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  192.168.1.182:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  fe80::e623:54ff:fe0c:3142:80
Thermostat, ecobee4,  192.168.1.21:1200
Thermostat, ecobee4,  fe80::4661:32ff:fe53:4801:1200
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  192.168.1.146:80
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  fe80::e623:54ff:fe0c:34c0:80
Mac-mini-3:.homebridge Brad$

**Comment by NorthernMan54** [comment] 2020-05-02 22:04
Was hombridge running when you ran that?  I don't see homebridge listed?

**Comment by bradc101** [comment] 2020-05-02 23:04
Yes, Homebridge was for sure running when I ran it - scrolled back in my window just to make sure. Since you asked about the Homebridge version, it occurred to me that I updated it right in the middle of all this, so here is what I did just now:
1. Downgraded Homebridge to 1.0.3. When I brought the server up, my dummy switches were discovered correctly!
2. Ran mdns-diagnostics. Here is the output - homebridge is now listed.
Mac-mini-3:.homebridge Brad$ mdns-diagnostics
Basestation, VMB4000,  192.168.1.15:35505
iHome SmartPlug-398D6C, iSP8,  192.168.1.64:80
iHome SmartPlug-398D6C, iSP8,  fe80::82a5:89ff:fe39:8d6c:80
iHome SmartPlug-76D2B5, iSP6X,  192.168.1.55:80
iHome SmartPlug-76D2B5, iSP6X,  fe80::82c5:f2ff:fe76:d2b5:80
iHome SmartPlug-18E078, iSP6X,  192.168.1.90:80
iHome SmartPlug-18E078, iSP6X,  fe80::429f:38ff:fe18:e078:80
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  192.168.1.146:80
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  fe80::e623:54ff:fe0c:34c0:80
Thermostat, ecobee4,  192.168.1.21:1200
Thermostat, ecobee4,  fe80::4661:32ff:fe53:4801:1200
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  192.168.1.23:80
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  fe80::207:a6ff:fe0c:f5bb:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  192.168.1.235:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  fe80::207:a6ff:fe0a:feff:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  192.168.1.173:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  fe80::207:a6ff:fe07:86ee:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  192.168.1.169:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  fe80::e623:54ff:fe0c:2f1c:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  192.168.1.182:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  fe80::e623:54ff:fe0c:3142:80
Homebridge 5E53, Homebridge,  192.168.1.234:51826
Homebridge 5E53, Homebridge,  fe80::ca:fe0:e314:4774:51826
Mac-mini-3:.homebridge Brad$ 

3. Went back to Homebridge 1.0.4. Surprisingly, switches were discovered normally. Added a few more just to make sure, but it all worked as expected. I have no explanation for this behavior.
4. Added back the Wink3 plugin. That also works correctly, and does not interfere with alexa discovery.

Here is the output of mdns-diagnostics after doing all of the above:

Mac-mini-3:.homebridge Brad$ mdns-diagnostics
Homebridge 5E53, Homebridge,  192.168.1.234:51826
Basestation, VMB4000,  192.168.1.15:35505
iHome SmartPlug-18E078, iSP6X,  192.168.1.90:80
iHome SmartPlug-18E078, iSP6X,  fe80::429f:38ff:fe18:e078:80
iHome SmartPlug-76D2B5, iSP6X,  192.168.1.55:80
iHome SmartPlug-76D2B5, iSP6X,  fe80::82c5:f2ff:fe76:d2b5:80
iHome SmartPlug-398D6C, iSP8,  192.168.1.64:80
iHome SmartPlug-398D6C, iSP8,  fe80::82a5:89ff:fe39:8d6c:80
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  192.168.1.23:80
Leviton Switch-0CF5BB, Leviton Switch-0CF5BB,  fe80::207:a6ff:fe0c:f5bb:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  192.168.1.169:80
VOCOlinc-L1-0c2f1c, VOCOlinc-L1-0c2f1c,  fe80::e623:54ff:fe0c:2f1c:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  192.168.1.182:80
VOCOlinc-L1-0c3142, VOCOlinc-L1-0c3142,  fe80::e623:54ff:fe0c:3142:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  192.168.1.173:80
Leviton Dimmer-0786EE, Leviton Dimmer-0786EE,  fe80::207:a6ff:fe07:86ee:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  192.168.1.235:80
Leviton Dimmer-0AFEFF, Leviton Dimmer-0AFEFF,  fe80::207:a6ff:fe0a:feff:80
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  192.168.1.146:80
VOCOlinc-L1-0c34c0, VOCOlinc-L1-0c34c0,  fe80::e623:54ff:fe0c:34c0:80
Thermostat, ecobee4,  192.168.1.21:1200
Thermostat, ecobee4,  fe80::4661:32ff:fe53:4801:1200
Mac-mini-3:.homebridge Brad$ 

I have no explanation for this behavior. My stuff is working now, but I would be happy to continue to work on this with you as needed. Please accept my thanks for all your hard work.

**Comment by NorthernMan54** [comment] 2020-05-04 22:35
Tks for sharing this diagnostic, I'm working with the Homebridge team on resolving and this is very helpful

**Comment by bradc101** [comment] 2020-05-04 23:37
Ok. Let me know if I can help in any way.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NorthernMan54** [comment] 2020-09-10 01:24
This has been resolved in the latest homebridge release.

**Closed** 2020-09-10 01:24 UTC
